### ISSUE TITLE
Renaming Sidebar

### ISSUE THREAD

**Issue by jjlangholtz** [tiy-durham-q3-rails/freeshelf#45]
Now that we have a link for videos on the sidebar I think it makes more sense to rename 'Home' to 'Books'. Perhaps a better alternative would be to have 'Home' index all books and videos and add a 'Books' link to index books.

Thoughts?

**Comment by andrewhooge** [comment]
Josh,

Makes sense to me...definitely a better experience.  Would you suggest a
Home Index that shows books/videos and separate book and video indexes?

Andrew

On Sun, Jul 13, 2014 at 10:14 PM, Joshua Langholtz <notifications@github.com
